# ============================================================
# Pipeline Parameters (params.yaml)
# ============================================================

# -------------------- Inputs --------------------
samplesheet: "./samplesheet.csv"

# -------------------- Reference Base (informational) --------------------
ref_base: "/fs04/vh83/pipeline_reference"

# -------------------- Core References --------------------
reference: "/fs04/vh83/pipeline_reference/genomes/hg37/human_g1k_v37_decoy.fasta"
reference_fai: "/fs04/vh83/pipeline_reference/genomes/hg37/human_g1k_v37_decoy.fasta.fai"
bed: "/fs04/vh83/pipeline_reference/panels/Agilent_custom/Prostate_ctDNA_v3/3388551_Covered_b37.slop.bed"

# -------------------- Outputs --------------------
outdir: "${launchDir}/output"

# -------------------- VarDict --------------------
min_af: 0.05
tumor_min_reads: 3
germline_min_reads: 1

# -------------------- VEP --------------------
# These params kinda have to fit what's inside the vep_cache_dir I think, as VEP the tool looks for: <dir_cache>/<species>/<version>_<assembly>

vep_species: "homo_sapiens"
vep_version: "115"
vep_assembly: "GRCh37"
vep_cache_dir: "/fs04/vh83/pipeline_reference/annotations/vep_cache/115/RefSeq/"


# -------------------- SnpEff / Annotation --------------------
# where your refs live on the host
refs_dir: "/fs04/vh83/pipeline_reference/"
#mane_dir: "/fs04/vh83/pipeline_reference/annotations/snpeff_cache/h38/MANE/1.2/"
clinvar_vcf: "/fs04/vh83/pipeline_reference/annotations/clinvar/20260208/GRCh37/clinvar.vcf.gz"

# Which ClinVar INFO fields to keep
clinvar_info: "CLNSIG,CLNREVSTAT,CLNDN,CLNVC,ALLELEID,CLNVCSO,RS"

#snpeff_genome: "GRCh38.99"
#snpeff_data: "/snpeff_data"

# -------------------- MultiQC --------------------
multiqc_extra_args: ""
